### ISSUE TITLE
missing storage_pairs method

### ISSUE THREAD

**Issue by pgherveou** [paritytech/subxt#1011]
Looks like this method is not exposed in subxt, would be nice to add it 
https://paritytech.github.io/substrate/master/sc_rpc_api/state/trait.StateApiClient.html#method.storage_pairs

**Comment by jsdw** [comment]
Two notes on the RPC calls:

1. The RPC calls that we expose are generally just those that Subxt's higher level interface need to function. This is in part because..
1. At some point after Pierre's new RPC API is stabilised, the "old" methods will be removed (either sooner if we can write shims to use old methods where needed, or later if we want to wait for the APis to be widely available). At this point, Subxt will expose 100% of the "new" methods and 0% of the "old" ones.

For these reasons I'm generally against exposing any methods at the RPC layer that Subxt isn't using. We do want to have a pass over the storage interface at some point though, and that pass will take into account what the new RPC methods are capable of doing and not necessarilt what's possible with the old ones :)

That all said, you can use the "low level" rpc interface (`api.rpc().request()` and `api.rpc().subscribe()`) to request or subscribe to whatever you need, and this interface won't be going anywhere :)

**Comment by pgherveou** [comment]
Thanks for the explanations @jsdw 

> At some point after Pierre's new RPC API is stabilised, the "old" methods will be removed (either sooner if we can write shims to use old methods where needed, or later if we want to wait for the APis to be widely available). At this point, Subxt will expose 100% of the "new" methods and 0% of the "old" ones.

Is there a PR somewhere that I can track?

**Comment by jsdw** [comment]
No single PR to track re stabliising; but see the geenral spec here:

https://github.com/paritytech/json-rpc-interface-spec/

And then we need to raise issues as we get to making the updates in substrate to catch up with the recent spec changes eg any RPC-Spec-V2 issue:

https://github.com/paritytech/substrate/issues?q=is%3Aissue+RPC-Spec-V2+is%3Aopen+author%3Alexnv

(@lexnv would you be able to group all of the V2 issues into a milestone or tracking issue please? :))

And then once things are settled and we've experimented with the API in Subxt etc we'll try to push for stabilising them (could be another 6 months or so I reckon)
