### ISSUE TITLE
Retreive decoded block data

### ISSUE THREAD

**Issue by f-squirrel** [paritytech/subxt#1013]
Is there a way to receive a block, iterate over events inside it, and see them decoded?

**Comment by niklasad1** [comment]
Yes, have look at https://github.com/paritytech/subxt/blob/master/subxt/examples/blocks_subscribing.rs

I think that's what you want to right? You can also decode specific events only with https://docs.rs/subxt/latest/subxt/events/struct.EventDetails.html#method.as_event

Perhaps we should add a separate examples for that because I also I had troubles find that.

**Comment by f-squirrel** [comment]
@niklasad1 thank you very much for help!

**Comment by jsdw** [comment]
Also you can look at the book, which has more context (a little less so in this area though):

https://docs.rs/subxt/0.29.0/subxt/book/usage/blocks/index.html

There's a specific page for events too:

https://docs.rs/subxt/0.29.0/subxt/book/usage/events/index.html

And these are all linked from the "main" book page here:

https://docs.rs/subxt/0.29.0/subxt/book/index.html#usage

Anyways, I'll close this now but please do create a new issue if you run into a problem!
