### ISSUE TITLE
Split runtime type generation from subxt-codegen 

### ISSUE THREAD

**Issue by DragonDev1906** [paritytech/subxt#1019]
I'm using subxt only for one thing: Decoding a `Vec<RuntimeEvent>` and extracting a list of events from a few pallets. I cannot use the `system.events` rpc call because I need a proof of inclusion. Using subxt to do this results in a compilation time increase of 10-30 Seconds, most likely because subxt creates so many types.

It would be nice if we could have more control over which types are created than just `runtime_types_only` and which pallets we want. While the unused types don't show up in the binary they do increase the compile time significantly.

The only ways (that I know of) to resolve this are:
- move the macro generation into a separate crate and re-export only what I need (probably with one crate per chain), that way this can at least be done in parallel, though it would still take a good amount of compilation time.
- Write a macro that throws away the generated code that is not needed before the compiler goes through type checking and borrow checking
- Codegen into a file and manually throw away things I don't need
- A combination of the above
- Write my own code generator

Except from `-Z time-passes`:
```
time:   4.519; rss:   59MB ->  225MB ( +166MB)	expand_crate
time:   4.520; rss:   59MB ->  225MB ( +166MB)	macro_expand_crate
time:  17.203; rss:  288MB ->  483MB ( +194MB)	type_check_crate
time:   8.308; rss:  483MB ->  638MB ( +156MB)	MIR_borrow_checking
time:   1.823; rss:  638MB ->  653MB (  +15MB)	MIR_effect_checkingdata
time:  19.701; rss:  749MB ->  979MB ( +230MB)	codegen_to_LLVM_IR
time:  23.271; rss:  749MB ->  979MB ( +229MB)	codegen_crate
time:  26.118; rss:  798MB ->  710MB (  -88MB)	LLVM_passes
time:   3.436; rss:  780MB ->  625MB ( -155MB)	finish_ongoing_codegen
```

Adding a second subxt macro makes these even slower.

PS: If you know of a way to proof which events happened or an easy way to decode the `system.events` storage to only extract events from a single pallet, please tell me.

**Comment by DragonDev1906** [comment]
The timings above is already with only the System pallet enabled when getting the metadata.

**Comment by jsdw** [comment]
I'm not in favour of adding more ways to strip down the generated code in Subxt-macro/codegen itself really, because each adds complexity that isn't relevant to the core use case of providing a compile-time interface to Subxt. Even the `runtime-types-only` feature I'm not a big fan of for this reason.

I think the ideal option would be to split out the type generation logic from Subxt-codegen into its own crate (quite probably entirely separate from Subxt (possibly something named `scale-*` since it's working with the scale type registry). We could then give it an interface that allows somebody to be very selective over exactly which types they want to generate output for. Subxt-codegen could then rely on this generator. for its more coarse type generation needs.

This has also come up elsewhere; @pmikolajczyk41 has wanted to be able to generate specific runtime types too.

**Comment by tadeohepperle** [comment]
Closing this, as [`scale-typegen`](https://github.com/paritytech/scale-typegen) is now fully integrated into the newest release (0.34.0) of subxt.
