### ISSUE TITLE
Subxt Macro for creating a `subxt::Config` from a given Runtime.

### ISSUE THREAD

**Issue by tadeohepperle** [paritytech/subxt#1036]
The creation of a struct that implements `Subxt::Config` for a given substrate chain is quite tedious and requires the manual lookup of many types that are sometimes hard to find. I am currently writing a guide about how to do that manually.

It would be nice to have a custom derive macro that creates an implementation of `subxt::Config` given a valid `Runtime`.
For example if we want to get the Config (including extra params, etc...) for the Polkadot Asset Hub Parachain (formerly known as Statemint) we could do something like this:

```rs
use asset_hub_polkadot_runtime::Runtime;

#[derive(subxt::Config)]
#[config(runtime = Runtime)]
struct Bar;
```

This would automatically get the appropriate types from the various traits the `asset_hub_polkadot_runtime::Runtime` implements and use them as the associated types of subxt::Config.

I am about 70% sure a proc macro could be able to do this.

**Comment by jsdw** [comment]
Just to put my 2 cents here (we've already chatted about this):

1. One of the downsides of importing the `Runtime` like this is that you end up with a ton of substrate crates being imported, which likely impacts compiling the code to wasm. You also potentially end up with version mismatches and things which make things like `PairSigner` not work as expected (and you may even want to connect to multiple runtimes at once which exacerbates the issue.
2. Some config traits come with associated logic (eg how do I sign something to get to the Signature type, or how do I hash something). I think we could probably provide some sort of "dynamic" config values which could check the metadata to see which hashing type or signature type or whatever is needed and support "standard" cases, while still letting the user manually configure things for more exotic cases. (this might require additions to the metadata).
3. I wonder whether there is any scope for inspecting the WASM runtime code and using this to generate some config? Eg I could imagine code like the following (which may need trait changes):

```rust
struct WasmConfig(Arc<wasm_blob>);

impl Config for WasmConfig {
    type Index = WasmIndex,
    type Hasher = WasmHasher,
    type Signature = WasmSignature,
}

// these structs use the wasm code to dynamically hash or whatever:
struct WasmHasher(Arc<wasm_blob>);
struct WasmSignature(...);
```

4. `ExtrinsicParams` are an interesting one. We have the relevant metadata for these already, so I could imagine tweaking the interface a little so that it was possible to provide `EncodeAsType` values or whatever to dynamically encode and decode things to them, possibly. But! These things usually have weird `Encode` impls or whatever because they want to be super compact. So Perhaps one approach here is to provide some impl of the individual signed extensions like `CheckEra`, `CheckNonce` or whatever, and allow Config which let you provide these dynamically and used whatever was needed based on metadata, or otherwise just make it easy to customise the Config for chains by letting peopls set `ExtrinsicParams` to a tuple of these or whatever. Basically, I think we can make the `ExtrinsicParams` story better here, though we need to keep in mind that it's good to have the ability to provide a really nice API here, so I'm mainly thinking about making things more flexible but not taking away the ability to have a nice interface. Needs thought!

**Comment by jsdw** [comment]
I'm going to close this in favour of using metadata to allow us to make more types "dynamic" :)
