### ISSUE TITLE
Query regarding static storage.   

### ISSUE THREAD

**Issue by nakul1010** [paritytech/subxt#1040]
The `0.25.0` version. had support for  `StaticStorageAddress` and `DecodeStaticType` does the new version support the static type? 

The `0.25.0` version I had the following type
`pub type KeyStorageAddress<T> = StaticStorageAddress<DecodeStaticType<T>, (), (), Yes>;`

I have updated it according for `0.29.0` version
`pub type KeyStorageAddress<T> = Address<StaticStorageMapKey, T, (), (), Yes>;`

While iterating through the storage 
```Rust
        let mut iter = self.api.storage().at_latest().await?.iter(key_addr, DEFAULT_PAGE_SIZE).await?;
        while let Some((key, value)) = iter.next().await? {}
```

i am getting the following error: ``` the trait `IntoVisitor` is not implemented for `T` ```

**Comment by jsdw** [comment]
Could you provide a more complete example perhaps? Offhand I'd guess that the `T` you're providing isn't correct!

**Comment by jsdw** [comment]
Basically, the way to make types work in the new version is to have them implemenbt `scale_encode::EncodeAsType` and `scale_decode::DecodeAsType`. If you own the types, normally you can just use the corresponding derive macros from each crate so you'd end up with eg:

```rust
#[derive(scale_encode::EncodeAsType, scale_decode::DecodeAsType)]
struct CurrencyId { ... }
```

The `Static` type exists for when this isn't possible, and it makes anything that implements `codec::Encode` and `codec::Decode` also implement those traits.

The reason we now want these traits to be implemented is because `EncodeAsType` and `DecodeAsType` impls make use of metadata to help guide how types are SCALE encoded and decoded. `codec::Encode` and `codec::Decode` on the other hand just attempt to encode and decode bytes based on the static shape of the type and with no regard for what the metadata says. Anything wrapped in `Static` has this same limitation, so it's always preferable to implement the traits if you can :)

**Comment by nakul1010** [comment]
@jsdw thanks for the swift response.
