### ISSUE TITLE
Extend current light-client support to validate_transaction

### ISSUE THREAD

**Issue by vivekvpandya** [paritytech/subxt#1054]
Question:

Is it possible to extend current light-client support in subxt to have something similar to https://github.com/smol-dot/smoldot/blob/main/light-base/src/transactions_service.rs#L1133 ?

Basically here idea is that given a TX in encoded bytes and block_hash subxt should be able to validate if transaction is already included via smoldot light client. 

If this is feasible way what code is required for this?

**Comment by jsdw** [comment]
At the moment, the light client support is only experimental and the light client is basically used as a backend on which to make RPC requests to (ie subxt is a high level wrapper around the RPC interface of a node).

It's possible that we could either:
1. Expose the light client that we're using behind the scenes in some way, so that one can make use of other light client functionality, or
2. Add to the `LightClient` struct some functionality to do things like this.

I'm generally in favour of (1) at the moment, since it's more generic and avoids us needing to expose a bunch of light-client specific functionality at the moment.

In the future though, we'd like the light client interface to be the primary way to use Subxt to interact with chains. When that time comes (there's a bunch of work to stabilise it still which is ongoing), I think we could look at exposing higher level interfaces in Subxt to other light client functionality, or generally just take advantage of it a bit better in Subxt (which would play nicely with (1), anyway). Ultimately for this, we might end up having a `LightClient` trait which extends `OnlineClient` or something and allows us to expose additional light client specific stuff.

**Comment by jsdw** [comment]
I'm going to close this as I don't think there is actually anything to do here.

If you want to find out whether a transaction is in some block via Subxt, I think you can use code like this:

```rust
// Create a client (point it whereever you want or use light client etc):
let api = OnlineClient::<PolkadotConfig>::from_url("wss://rpc.polkadot.io:443").await?;

// Fetch a block by hash:
let mut block = api.blocks().at(block_hash).await?;

let exts = block.extrinsics().await?;

for ext in exts.iter() {
    let ext_hash = PolkadotConfig::Hasher::hash_of(ext.bytes());
    // check if ext_hash matches the one you're looking for.
}

Ok(())
```

One thing that I think we could add to make this a touch nicer is a means to hand back the extrinsic hash, so that you don't have to manually hash the bytes :)
