### ISSUE TITLE
Querying for old metadata

### ISSUE THREAD

**Issue by kylezs** [paritytech/subxt#1123]
Looking to upgrade from subxt 0.26 to 0.31 and I noticed that it's no longer possible to query for metadata at a particular block height. 

Previously querying the metadata at the particular block height was useful because it meant that it was possible to decode events from blocks before the last runtime upgrade boundary. Is there something in the new metadataV15 / subxt that is now able to decode events before the last runtime upgrade boundary?

**Comment by jsdw** [comment]
How did you do this previously; via the underlying RPC call?

A couple of options are:

1. Copy the old RPC call locally and have it take in the RPC client and then use that.
2. If the chain/node you're talking to is uptodate enough to serve V15 metadata, then the "proper" way to fetch metadata at a block is via the runtime APIs. The static call isn't the most helpful because you have to decode it still but it's something like this:
   ```rust
   use codec::Decode;

   let runtime_query = polkadot::apis().metadata().metadata();
   let metadata_bytes = api.runtime_api().at(block_hash).call(runtime_query).await?;
   let metadata = subxt::metadata::Metadata::decode(&mut &*metadata.0)?;
   ```
3. If not, you can also do the same using the "raw" version of the call (see https://github.com/paritytech/subxt/blob/master/subxt/examples/runtime_apis_raw.rs and change `at_latest()` for `at(block_hash)`.

(note that those call examples are both using the "old" metadata API which returns V14 metadata. Use `polkadot::apis().metadata().metadata_at_version(15)` to ask for V15 metadata using the newer calls.)

**Comment by kylezs** [comment]
There's still the `metadata_legacy` query which is on the RPC, so wouldn't need to copy it, if we did want to go that way, but I think for our use case now we can just assume that the nodes will always be returning v15 metadata and do away with the old.

**Comment by kylezs** [comment]
```rust
let runtime_query = polkadot::apis().metadata().metadata_at_version(15);
```

Trying to use this method but getting:
```
 let runtime_query = polkadot::apis().metadata().metadata_at_version(15);
    |                                          ^^^^^^^^ method not found in `RuntimeApi`
    ```
 I tried expanding the macro to see if I was missing some trait or what not, but given I was calling it from the same file the macro was used in, seems unlikely. The metadata downloaded is from a polkadot node the other day.

**Comment by jsdw** [comment]
> There's still the metadata_legacy query which is on the RPC

One thing to note is that an upcoming release will ditch some of the old RPC methods that Subxt doesn't actually use. The reason for this is that we will slowly be moving towards supporting the new V2 RPC methods (https://paritytech.github.io/json-rpc-interface-spec/). 

We'll also be changing how to make RPC calls a bit as we move to supporting both old and new APIs in parallel (and so move towards having a common "backend" interface that both sets of methods can implement). 

But that said, you'll still be able to call whatever RPC methods manually and copy any code from how Subxt made the calls previously if anything you want goes away (mostly the methods we expose are really simple wrappers around raw calls anyway).

**Comment by kylezs** [comment]
Think the question is answered in here anyway. Thanks.
