### ISSUE TITLE
Support decoding signed extensions from extrinsics in blocks

### ISSUE THREAD

**Issue by f-squirrel** [paritytech/subxt#1124]
I tried looking in the calls, e.g., `polkadot::Call::Balances`, `polkadot::Call::Staking`, etc. 
I reviewed extrinsic events, such as `Transfer`, `Nominate`, and many others. But I was unable to find this information.

Does `subxt` provide such functionality? If not, what is the way to retrieve this information?
I assume it is possible because many Polkadot [explorers](https://polkadot.subscan.io/extrinsic/16711660-2) provide this information.

**Comment by jsdw** [comment]
Currently, we don't expose a way to get at this stuff; the account nonce is in the signed extensions of the extrinsic (and these can vary depending on the chain). At the moment we just skip over these when parsing extrinsics.

We could probably return something like a `Vec<(String, scale_value::Value)>` containing details for each of the signed extensions, and there you could locate the "CheckNonce" extension and find the nonce.

Alternately we could probably just look for and extract a couple of details from signed extensions if they are in use (since eg "CheckNonce" would almost always be used).

**Comment by jsdw** [comment]
I think I'd be inclined to add an API like this:

```rust
let tx: ExtrinsicDetails = todo!();

let signed_exts: SignedExtensions = tx.signed_extensions();

// return all of the bytes associated with the signed extensions:
signed_exts.bytes()

// Can look for a particular extension, None if not found.
if let Some(ext) = signed_exts.find("CheckNonce") {
    // dynamically decode extension bytes to a Value to inspect.
    let val = ext.value();
    // just get the bytes/type ID for this extension to do what you like with:
    ext.bytes();
    ext.type_id();
}

// We could also expose a couple of "high level" things which
// would work so long as the relevant signed extension is used like:
ext.tip() -> Result<Option<u128>, Error>
ext.nonce() -> Result<Option<u64>, Error>

// I'd expect most chains would expose that stuff, and `None` if extension not found.
```

This would generally allow access, with a couple of specific helpers for common things.
