### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by prybalko** [paritytech/subxt#1136]
The latest `v0.31.0` version of `subxt` uses `jsonrpsee` version 0.16.2 that contains a high severity vulnerability in `webpki`.
https://rustsec.org/advisories/RUSTSEC-2023-0052.

I see that `master` is already updated to `jsonrpsee` version 0.20.0, but the new `subxt` version hasn't been published yet.

**Comment by jsdw** [comment]
An issue with releasing right now is that we have recently merged some larger breaking changes, and I'd like us to sit with and tidy them a little before releasing a new version of Subxt.

As I understand it, this vulnerability is to do with the underlying library validating certificate chains, which is only relevant in our case if you connect to a malicious server via HTTPS/WSS in the first place.

It also looks like `jsonrpsee` 0.20.0 still has the `webpki` crate in its tree anyway (whereas master does not). @niklasad1 would know more probably :)

If it turns out to be important, we could possibly backport some fix and do a patch release (eg 0.16.3) of `jsonrpsee` if that's feasbile (@niklasad1?)

**Comment by niklasad1** [comment]
Hey @prybalko 

I got it wrong but we have made jsonrpsee patch release v0.16.3. 

So if you just run `cargo update -p jsonrpsee` the vulnerability should go away :)

**Comment by prybalko** [comment]
Perfect, thanks!
