### ISSUE TITLE
BoxedPayload - How to Sign?

### ISSUE THREAD

**Issue by paradox-tt** [paritytech/subxt#1241]
Hey Subxt team,

I'm building an application that signs transactions over multiple chains.  I've opted to not use the `dynamic ` approach as I prefer to work with stronger types provided using the traditional approach.  I've noticed that in using this approach I have a lot of repeated code reliant on specific types generated by each chain's metadata.

To narrow this issue to a very specific scenario.. I would like to have a function that can sign a boxed payload, something along the lines of:

```
async fn sign(wss_url:&str, payload:BoxedPayload) -> Result<String, Box<dyn std::error::Error>> {

	let api = OnlineClient::<PolkadotConfig>::from_url(wss_url).await?;

	let signer = extrinsic_support::get_signer();

	let tx = api
		.tx()
		.sign_and_submit_then_watch_default(&payload, &signer)
		.await?
		.wait_for_finalized_success()
		.await?;

	Ok(format!("{}",tx.extrinsic_hash()))
}
```
With the above, I receive an error:

```
.sign_and_submit_then_watch_default(&payload, &signer)
    |          ---------------------------------- ^^^^^^^^ the trait `EncodeAsFields` is not implemented for `Arc<dyn EncodeAsFields + std::marker::Send + Sync>`
```
 
 I'm using BoxedPayload specifically because it can be defined in Traits without the need for a workaround.
 
 Looking forward to your guidance,
 
 Regards,
 Will | Paradox

**Comment by jsdw** [comment]
Ah interesting! `BoxedPayload` was added originally because I had a plan for it, but that didn't pan out and it never really ended up being used, which also meant it avoided being tested! 

So, I think the issue here is that `BoxedPayload` wraps the call data in an `Arc`, and at a guess, there is no blanket implementation like `impl <T: EncodeAsFields> EncodeAsFields for Arc<T>`. 

To fix this, we should make sure that we add at least these impls (and a test somewhere to actually check that they work):

```rust
impl <T: EncodeAsFields> EncodeAsFields for Arc<T>
impl <T: EncodeAsFields> EncodeAsFields for Box<T>
impl <T: EncodeAsFields> EncodeAsFields for Rc<T>
```

In the mean time @paradox-tt, could you change the signature of your call to something like:

```rust
async fn sign<P: TxPayload>(wss_url:&str, payload:P) -> Result<String, Box<dyn std::error::Error>> {
```
Hopefully this should work for all of your payloads in the same way, avoiding the boxing issue.

If you do need to box the payloads, you might be able to manually box them yourself using a newtype which you _can_ impl EncodeAsFields on, something like this (untested):

```rust
fn box_payload<T: TxPayload>(payload: T) -> MyBoxedPayload { ... }

type MyBoxedPayload = Payload<BoxedCallData>;

struct BoxedCallData(Arc<dyn EncodeAsFields + Send + Sync + 'static>);

impl EncodeAsFields for BoxedCallData {
    fn encode_as_fields_to(
        &self,
        fields: &mut dyn FieldIter<'_>,
        types: &PortableRegistry,
        out: &mut Vec<u8>,
    ) -> Result<(), Error> {
        self.0.encode_as_fields_to(fields, types, out)
    }
}
```

>  I've noticed that in using this approach I have a lot of repeated code reliant on specific types generated by each chain's metadata.

This might not be a helpful comment but just in case: If the pallet's that you're communicating with are the same across different chains, then you should be able to get away with generating the metadata for one chain and then reusing it across others.

You'll know if this doesn't work, because if it's actually not the same, then trying to eg submit a transaction (or whatever it is) will result in an `IncompatibleCodegen` error. Might be worth a shot? :)

Anyway, lemme know if that helps!

**Comment by paradox-tt** [comment]
Thanks for the quick reply, I'll work on this tonight and response soonest.

**Comment by paradox-tt** [comment]
Just to give some updates:

1.  The code below worked  
`async fn sign<P: TxPayload>(wss_url:&str, payload:P) -> Result<String, Box<dyn std::error::Error>>`

I originally tried `async fn sign(wss_url:&str, payload:Box<dyn TxPayload>) -> Result<String, Box<dyn std::error::Error>>` and got myself into a world of headache.  Thanks again.

2. This did not work or didn't work due to my unfamiliarity with Rust.
```
fn box_payload<T: TxPayload>(payload: T) -> MyBoxedPayload { ... }

type MyBoxedPayload = Payload<BoxedCallData>;

struct BoxedCallData(Arc<dyn EncodeAsFields + Send + Sync + 'static>);

impl EncodeAsFields for BoxedCallData {
    fn encode_as_fields_to(
        &self,
        fields: &mut dyn FieldIter<'_>,
        types: &PortableRegistry,
        out: &mut Vec<u8>,
    ) -> Result<(), Error> {
        self.0.encode_as_fields_to(fields, types, out)
    }
} 
```

3.  Using metadata generated by one chain for use on other chains did not work.  It seems I'm back to duplicating and renaming code for each chain.  It would be good to somehow merge metadata from multiple chains into one with adequate referencing or have object safe Traits for types like RuntimeCalls or types used for queries.

Dynamic queries seems appropriate but maybe it's a shortcoming of my understanding... I'm able to execute the query but the values of complex types are usually not well formed.

**Comment by jsdw** [comment]
> Using metadata generated by one chain for use on other chains did not work.

Which errors or issues did you encounter here?

> It would be good to somehow merge metadata from multiple chains into one with adequate referencing or have object safe Traits for types like RuntimeCalls or types used for queries.

I see pallets as the units of code that are interesting, and my hope is that if you generate code for a pallet (regardless of where it comes from), and that pallet is the same in several places, then you should be able to re-use that generated code in those places. If you hit an `IncompatibleCodegen` error, then it means that something is different in the different places and you'd need different generated code.

There may be some scope for de-duplicating some of the generated types and interfaces though. The upside would be that there is less total generated code, but the downside is that we'd need to do compare all of the types to see what can be reused, merge them together in the type registry (which would involve rewriting IDs etc) and handle duplicate names when they do differ. I'm not sure that the added complexity would actually be worth it.
