### ISSUE TITLE
reconnecting rpc client

### ISSUE THREAD

**Issue by niklasad1** [paritytech/subxt#1423]
## What's the current behavior

Currently, subxt has recently added experimental support for a reconnecting rpc client, which is primarily
for users of the legacy RPC API

The main benefits of an "automatic reconnecting client" are as follows:
- Automatically reconnect on spurious connection hickups
- Avoid re-create all active subscriptions; for instance, it is possible that plenty of storage subscriptions are lost and need to be re-subscribed.
- The API for reconnecting/understand when a connection is closed is complicated in subxt
- The subscription API in subxt may return None when the connection is closed or that the subxt can't keep up with the server (the server is producing items faster than subxt can consume).
- Rotate between a list of endpoints (not supported yet).

Then the drawbacks are:
- Subscription messages may be lost when reconnecting.
- Subscription can have side effects, such as `submitAndWatch`
- Automatic re-connecting doesn't work well for the RPC spec v2 chain API, the "chain_head_unstable_follow subscription" returns the subscriptionID which will be used to query further states from the chain_head API. Thus, when reconnecting, the subscription ID must be "updated" to use the new one, and the old subscription ID from the old connection may not work.

## What subxt needs

subxt needs two different behaviors as long as it's compatible with both the RPC APIs.

### Legacy RPC

Provide the notion that users can decide whether they want to re-subscribe on certain subscriptions or not.

```rust
let rpc = Client::builder()
// This is the global default policy, unless specified elsewhere this is used.
.retry_policy(ExponentialBackoff::from_millis(100).max_delay(Duration::from_secs(10)))
// For the `tx_submitAndWatch` we don't attempt at resubmitting the tx again; and let the user handle this if wanted
.local_policy(subxt::rpc::Method::TransactionSubmitAndWatch, Policy::DoNotRetry)
```

It's basically not possible to get the state of transaction if connection is closed and up to the user if re-submit or not for such cases.

Use this as the default behavior.

### RPC v2 spec

Because the API is very different it should be quite straight forward to implement auto-reconnect directly in subxt such as andlet users decide whether
the want to create some subscriptions, calls on startup... which is "initial"

```rust
async fn client_auto_reconnect(
    initial: Vec<RpcCalls>,
    retry_policy: RetryPolicy,
) -> Result<(), ()> {
    let driver = create_rpc_backend(initial_state.clone(), retry_policy).await?;

    loop {
        // Reconnect if err
        if let Err(RpcDisconnect(r)) = driver.next() {
            driver = create_rpc_backend(initial.clone(), retry_policy).await?;
        }
    }
}
```

Also implement custom re-connecting logic should much easier to implement for users. It just a stream that returns an Err(Disconnect) then handle it. 

### Both

Improve subscription API such that indicates clearly whether the connection was closed or that subscription couldn't keep with the server. See https://github.com/paritytech/jsonrpsee/pull/1255 which is needed for this.

//cc @jsdw thoughts?

**Comment by jsdw** [comment]
One question here is: how much work should the RPC client do versus Subxt itself? 

In my mind, either (a) the RPC client could handle re-establishing the connection (and nothing else), or (b) the RPC client is "dumb" and Subxt internally handles all reconnect logic.

- The advantage of (a) is that it's a natural place to configure retry policy or whatever (and others can write clients with different reconnect behaviour).  On disconnect, the client emits an error (`DisconnectedWillReconnect`) to let Subxt backends know what's going on.
- The disadvantage of (a) is that it's harder to plug in custom RPC clients if you don't care about this reconnect behaviour and would rather Subxt took care of it all. Also more of a gap between backend and reconnect logic may make it a bit harder to do precisely what we want in the backend.

If we went with (a) then users would configure or use an RPC client with whatever retry behaviour they want:

```rust
// users can provide their own impl of this
let client =RpcClient::builder()
    .retry_policy(ExponentialBackoff::from_millis(100).max_delay(Duration::from_secs(10)))
    .build();

let backend = Backend::new(client);
```

If we went with (b) then reconnect stuff would all be on a specific backend instead.

**I'm slightly leaning towards (a) here but I think either option would work pretty well in the end!**

In either case, then as you say we'd need to modify the legacy and unstable backends differently. for instance if we go with (a) then:

- The legacy backend subscriptions etc should catch `DisconnectedWillReconnect` and wait for the RPC client to do so (perhaps that would require another event to be emitted from the RPC client like `Reconnected` so we know when to start trying to re-subscribe). The `DisconnectedWillReconnect` error should be forwarded to users so that ultimately they can decide whether to let the thing reconnect or drop the calls/subscriptions when disconnect happens.
- The unstable`follow_stream` would need to _not_ stop itself when a `DisconnectWillReconnect` is emitted and instead wait for a `Reconnected` and then re-subscribe itself (like it already does autoamtically when "stop" event seen). Again, `DisconnectedWillReconnect` (and maybe in both cases, `Reconnected` too?) should be propagated up so that in `follow_stream_driver` the user can decide to keep going or not. We'd need subscriptions etc in the higher level `UnstableBackend` impl to recreate themselves against the new follow subscription etc, which may require tracking some things.

If we went for (b) then each individual backend would have the reconnect logic inside it instead. We'd probably still want to emit somehting like `DisconnectedWillReconnect` and then `Reconnected` to give users a choice to drop things at that point or go ahead and reconnect (knowingf that events etc may be lost).

I like the idea of the user being able to configure backends with specific behaviour ie the `.local_policy(subxt::rpc::Method::TransactionSubmitAndWatch, Policy::DoNotRetry)` stuff.

This will need some experimentation I think; we'll just need to try an approach and see how it works out :)

> Improve subscription API such that indicates clearly whether the connection was closed or that subscription couldn't keep with the server.

Makes sense! Perhaps this can be a value given to `DisconnectedWillReconnect`, so that impls will try reconnecting regardless of reason, but users can interrogate the reason and decide not to try again in some cases eg if they are too slow.

**Comment by niklasad1** [comment]
I have looked a bit closer at this and I agree with subxt's reconnecting rpc client should only reconnect.
Previously I had in mind that subxt could be actually be opinionated and retry calls without side-effects but changed my mind now.

Because subxt has the backend trait that roughly looks like

```rust
pub trait Backend {
   async fn method_call(&self) -> Result<T, Error> { ... }
   async fn subscribe(&self) -> Result<Subscription<T>, Error> { ... }
}
```

Because we know have `Error::DisconnectedWillReconnect` it should be trivial to someone to write their own retry logic by doing for plain rpc calls:

##### Example code for retry-able rpc call

```rust
let res = loop {
   match client.method_call().await {
     Ok(res) => break Ok(res),
     Err(e) if e.is_disconnected_will_reconnect() => {
        // use tokio_retry or something
        tokio::time::sleep(Duration::from_secs(5)).await;
     }
     Err(e) => break Err(e),
  }
};
```

However, subscriptions are a bit trickier and if subxt could provide wrapper types that provides "resubscribing" I would be happy with it.

```rust
/// Runtime version subscription.
pub struct RuntimeVersionSubscription<T: Config> {
    backend: LegacyRpcMethods<T>,
    stream: RpcSubscription<RuntimeVersion>,
}

impl<T: Send + Sync + Config> RuntimeVersionSubscription<T> {
    /// Returns the next item in the stream. This is just a wrapper around
    /// [`StreamExt::next()`] so that you can avoid the extra import.
    pub async fn next(&mut self) -> Option<Result<RuntimeVersion, Error>> {
        StreamExt::next(self).await
    }

    /// Resubscribe to the subscription.
    pub async fn resubscribe(self) -> Result<Self, Error> {
        self.backend.state_subscribe_runtime_version().await
    }
}

impl<T: Config> std::marker::Unpin for RuntimeVersionSubscription<T> {}

impl<T: Send + Sync + Config> Stream for RuntimeVersionSubscription<T> {
    type Item = Result<RuntimeVersion, Error>;

    fn poll_next(
        mut self: Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> Poll<Option<Self::Item>> {
        self.stream.poll_next_unpin(cx)
    }
}
```


##### Example code for retry-able rpc subscription

```rust
    while let Some(block) = blocks_sub.next().await {
        let block = match block {
            Ok(b) => b,
            Err(Error::Rpc(RpcError::DisconnectedWillReconnect(err))) => {
                println!("Disconnected {err}; resubscribe");
                blocks_sub.resubscribe().await?;
                continue;
            }
            Err(e) => {
                return Err(e.into());
            }
        };
   }
```

**Comment by jsdw** [comment]
Nice, I'm onboard with all of that!

In summary, RpcClient only reconnects the WS but doesn't do anything else, and let the backend impls decide how to handle it (we can prob write helper functions in subxt to help us out if we find ourselves duplicating any retry logic yup)
