### ISSUE TITLE
Unable to parse Acala metadata

### ISSUE THREAD

**Issue by trevor-crypto** [paritytech/subxt#1436]
Hi, I'm using subxt_metadata to parse metadata retrieved from the substrate node RPC call `state_getMetadata()` into the `subxt_metadata::Metadata` which works really well for most parachains except Acala.

The error is not very helpful:
```
Error: Error { cause: None, desc: "Cannot try_into() to Metadata." }
```

Here is [a minimal working example](https://github.com/trevor-crypto/acala-repro/blob/master/src/main.rs)

Any thoughts on if this is a subxt or an Acala problem would be greatly appreciated! Thanks.

Related: https://github.com/AcalaNetwork/Acala/issues/2708

**Comment by trevor-crypto** [comment]
After adding a dbg!
```rust
        metadata.map_err(|_e| {
            dbg!(_e);
            "Cannot try_into() to Metadata.".into()
        })

```

I can see the error!
```
_e = TypeNameNotFound(
    "ConvertEthTx",
)
```

**Comment by niklasad1** [comment]
The type is defined [here](https://github.com/AcalaNetwork/Acala/blob/97bfc236ef6a0023aa0eadb9d55c38208f4cf00e/primitives/src/unchecked_extrinsic.rs#L42-#L47) and adds `#[scale_info(skip_type_params(ConvertEthTx))]`.

So seems like a subxt indeed i.e, we should respect skip_type_params in the codegen.

**Comment by trevor-crypto** [comment]
@niklasad1 Thanks a lot for the quick reply! 

Is this a trivial fix where you can tell me exactly what to do and I can put up a PR? I'm comfortable with proc-macros and stuff, but not so familiar with SCALE

**Comment by trevor-crypto** [comment]
Just for clarity, [this is the line](https://github.com/paritytech/subxt/blob/1ea84c6cde94ac313dddf735e2fa3eda701cf06f/metadata/src/from_into/v14.rs#L285) that fails when the TypeParameter `ty` is `None`:

```
TypeParameter {          
    name: "ConvertEthTx",
    ty: None,            
},
```

**Comment by jsdw** [comment]
Somebody is looking into this already, but to give a quick update on my understanding of the issue:

You're downloading V14 metadata, and Subxt looks at the "extrinsic type" provided (in your case, the `AcalaUncheckedExtrinsic`) and expects certain generic parameters to exist to tell us some of the key types on an extrinsic. Because `AcalaUncheckedExtrinsic` has different params from the type we expected there (and one of the types is skipped, so no type info at all) it doesn't work out.

V15 metadata has well defined fields wherein the relevant types are provided, so when parsing V15 metadata Subxt doesn't need to try and "discover" them by looking on that extrinsic. Acala looks like it exposes V15 metadata, and so it might be worth giving that a try and seeing if you have more success?

**Comment by lexnv** [comment]
If you are calling into the runtime API, what is the result of `Metadata_metadata_versions`? This returns a list of supported versions by your node. Ideally, it should also contain a `15` metadata version. 

If the node returns in the list `15`, then you could make another runtime call to fetch the v15 `Metadata_metadata_at_version`.

Code example from subxt to run `Metadata_metadata_versions`:
https://github.com/paritytech/subxt/blob/1ea84c6cde94ac313dddf735e2fa3eda701cf06f/codegen/src/fetch_metadata.rs#L135-L144


Code example from subxt to run `Metadata_metadata_at_version`:
https://github.com/paritytech/subxt/blob/1ea84c6cde94ac313dddf735e2fa3eda701cf06f/codegen/src/fetch_metadata.rs#L179-L184

**Comment by lexnv** [comment]
Glad it worked!
