### ISSUE TITLE
Add ethereum compatible signer to subxt_signer?

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#1467]
Anybody can implement a custom signer for Subxt to sign things as they need.

An example which I put together just now which _seems_ to work for creating ethereum-compatible signatures and using `AccountId20`s is here:

https://gist.github.com/jsdw/13240f9341e433ea639b89d0d4235c8b

I'd be interested to check with other eth-compatible chains whether this solution works for all of them, and if so, it might be a good idea to add this in a more complete form to `subxt_signer`.

For now though, if anybody needs eth style signing, please check out the Gist above and let me know whether it works for you!

(this has come up previously in https://github.com/paritytech/subxt/issues/1037)

**Comment by ryanleecode** [comment]
On moonbeam this is working perfect. For other chains that claim they are "EVM compatible" i'm looking inside their metadata to see if there are any entries that are `Account20`. The issue with the implementation is trying to guess where the `Account20` is located under `eth_runtime::runtime_types`. Because its not always the same path say `eth_runtime_runtime_types::account:Account20`.

**Comment by jsdw** [comment]
> The issue with the implementation is trying to guess where the Account20 is located under eth_runtime::runtime_types. Because its not always the same path say eth_runtime_runtime_types::account:Account20.

It's totally ok if their `AccountId20`'s live in different places (that part is configued separately per chain anyway) :)
