### ISSUE TITLE
no_std support for subxt

### ISSUE THREAD

**Issue by melynx** [paritytech/subxt#159]
Currently there isn't any no_std support for substrate-subxt making it really difficult to craft extrinsics from within a restricted environment. Is there any planned support for no_std / alloc environments?

**Comment by DemiMarie** [comment]
I am not aware of any such plans on Parity’s end, though community contributions would be welcome.  That said, much of the client code is likely to be completely rewritten at some point.  Currently, each extrinsic requires manual effort in this repo, which just does not scale.  In the future, the client code will be generated from the chain metadata.

**Comment by jsdw** [comment]
Nowadays we have a `subxt-core` crate which contains the no-std compatible subset of subxt functionality (it does require `alloc` though; I think for non-alloc cases you're probably going to have to do something more manual as needed since we rely on it quite a lot!)

So I'll close this, and we can open new issues to address things missing from `subxt-core` or whatever :)
