### ISSUE TITLE
rpc subscription: provide `RpcError::Disconnected`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/subxt#1657]
After the latest version of jsonrpsee provides https://docs.rs/jsonrpsee-core/0.23.1/jsonrpsee_core/client/struct.Subscription.html#method.close_reason

subxt could introduce `RpcError::Lagged` if the subscription was closed because it lagged i.e, could not keep up with the server, not 100% convinced about this but could be useful I guess...

**Comment by jsdw** [comment]
For reference, here is the current RpcError:

```rust
pub enum RpcError {
    /// Error related to the RPC client.
    ClientError(Box<dyn std::error::Error + Send + Sync + 'static>),
    /// This error signals that the request was rejected for some reason.
    /// The specific reason is provided.
    RequestRejected(String),
    /// The RPC subscription dropped.
    SubscriptionDropped,
    /// The requested URL is insecure.
    InsecureUrl(String),
    /// The connection was lost and automatically reconnected.
    DisconnectedWillReconnect(String),
}
```

I'm actually surprised that there isn't an explicit `RpcError::Disconnected` variant to signal that the connection was terminated. Perhaps that could be added, maybe something like:

```rust
pub enum RpcError {
   // ...
   Disconnected(DisconnectReason)
}

pub enum DisconnectReason {
    // We can add specific reasons here that we think may be useful to people.

    // Or allow some custom message for other stuff:
    Custom(String)
}
```

I guess whether we add a variant or not should be based on whether we want it to be easy for people to match on it and handle that specific case. So then the question is; would anybody want special handing for the `Lagged` case, or should it just return `DisconnectReason::Custom("Connection terminated because client was too slow to keep up")`?

**Comment by niklasad1** [comment]
Yeah, I like `DisconnectReason`  but I think the reason is that we use the stream impl and it returns `None` when subscription is closed (which could caused that the connection was closed)

**Comment by jsdw** [comment]
Ah yeah ok; the stream could def return a Some(RpcError::Disconnected(..)` before returning `None` to indicate no more items. In the jsonrpsee_impl we have eg:

```rust
let stream = stream
    .map_err(|e| RpcError::ClientError(Box::new(e)))
    .boxed();
```

And I geuss that could pay more attention to the specific error there and turn it into a `Disconnected` variant in the right cases?

**Comment by niklasad1** [comment]
I don't think this is needed anymore once we stabilize to reconnecting rpc client... 

So closing this
