### ISSUE TITLE
Support multiple versions of Substrate

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/subxt#179]
Currently, backwards-incompatible metadata changes cause a nasty problem for subxt, and thus Ledgeracio.  The old version of subxt supports the old runtime, and the new version of subxt supports the new runtime.  However, the on-chain runtime upgrade can happen at any time, so there is no way to know when to switch without race conditions.

To solve this, subxt needs to support multiple incompatible runtime versions.  Support for a version will be added before it is proposed on-chain.  Support for a version will only be removed when all runtimes have migrated off of it.

**Comment by jsdw** [comment]
subxt does now allow you to run an update task in the background to attempt to keep metadata/runtimeversion bits in sync when a runtime update happens on a node you're connected to.

Additionallyt, if runtime updates break the static codegen, new validation logic will at least warn you now when attempting to interact with a ndoe (rather than breaking in much nastier ways).

We are also adding support for dynamic queries to be more flexible w.r.t talking to different runtimes, and if a runtime update fundamentally breaks codegen we try to fix this with backward compat in mind nowadays.

So, I think we're doing what we can here, but pelase raise a new issue (for visibility) if there is still a specific area that you think subxt could address better and we'll consider it :)
