### ISSUE TITLE
Decoding custom events

### ISSUE THREAD

**Issue by kylezs** [paritytech/subxt#269]
In the example [here](https://github.com/paritytech/substrate-subxt/blob/master/examples/transfer_subscribe.rs), the Event is decoded into a Wrapper struct, `TransferEvent` which is packaged with subxt in `balances.rs`, *not* from `pallet-balances` itself. 

In that case, when using custom events, is the pattern you're going for to have a wrapper for each custom pallet, containing a wrapper like what is done for `balances` in the example? Or am I missing something?

Also noted that there is an open issue [here](https://github.com/paritytech/substrate-subxt/issues/141) which potentially makes what I've written above irrelevant. Is there any progress on that front?

**Comment by ascjones** [comment]
Currently I'm working on https://github.com/paritytech/substrate/pull/8615 which will provide full type metadata for all pallet events. Once this in in we will likely overhaul the `subxt` API so that it can fully generate all the necessary types from the metadat for interacting with pallets. This new API is TBC, but you should be able to subscribe to custom events.

**Comment by kylezs** [comment]
@ascjones 
Thanks. Do you have an estimate on when this work will be done?

**Comment by ascjones** [comment]
Most likely a month of two away.

**Comment by ascjones** [comment]
Closed by #294
