### ISSUE TITLE
Support Runtime Metadata v13

### ISSUE THREAD

**Issue by shekohex** [paritytech/subxt#324]
Hello, any plans to support RuntimeMetadata v13?

**Comment by jsdw** [comment]
@ascjones I'd assume that this isn't a direction that we'd want to take, given the work involved in doing so, but I could be wrong?

**Comment by ascjones** [comment]
Indeed, `V13` does not contain enough information to generate all the necessary types. It would be possible provided some manual type mappings as in the "legacy" version of `subxt`.

But since it is now a legacy format I'm not sure it would be worth the effort to implement, though of course we are always open to contributions :)
