### ISSUE TITLE
Simplify and Streamify `EventSubscription`

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#413]
I reckon we could improve/simplify the `EventSubscription` struct. Some thoughts:

- Impl `Stream` (and so the `StreamExt` methods), so that the filtering logic can be (mostly?) moved out of this struct.
- Remove filtering on events from a specific block (if needed, add a separate method to obtain events from a single block which potentially returns the same event stream as we'd get here; this method could be reused in the `transaction.rs` stuff too if it existed).
- Remove filtering of events from a specific extrinsic (we get this now via the API in `transaction.rs`, and ideally it would be easy to manually filter the Stream for such events).
- Remove filtering of events by pallet/event index; make it easy to do so via the Stream.
- Update `transfer_subscribe` example to subscribe to events separately from making any transaction, and show off filtering and such. If needed, make transactions etc in a separate thread just to produce the desired events. (why? we shouldn't use this to get events for the current transaction as we have a proper API for that; but that's what the example seems to do).
- Possibly add other examples.

**Comment by paulormart** [comment]
Just read this issue and PR #423 and i'am fully supportive for the implementation of this feature. This is definitely a must have for this library :)

I'm currently using a [custom events subscription](https://github.com/turboflakes/subxt/blob/bfeefda78a7ebc49ebb55fef530c66e5b45e3443/src/custom_subscription.rs#L150) so that _block number_ and _authority index_ could be easily accessible [here](https://github.com/turboflakes/subxt/blob/develop/examples/custom_events_subscription.rs#L49)

**Comment by jsdw** [comment]
@paulormart , @lamafab and anybody else interested, feel free to check out #442 and leave feedback :)
