### ISSUE TITLE
what is "Not enough data to decode vector"  error?

### ISSUE THREAD

**Issue by paperfrog1228** [paritytech/subxt#460]
```
use std::any::Any;
use std::io;
use subxt::*;
use subxt::{ClientBuilder,DefaultConfig, DefaultExtra};
use subxt::codec::Decode;
use crate::sp_runtime::OpaqueExtrinsic;
use sp_runtime::{
    generic::{
        UncheckedExtrinsic
    },
    MultiSignature,
    AnySignature
};

#[subxt::subxt(runtime_metadata_path = "src/metadata.scale")]
pub mod polkadot {}

type Address = u64;
type Call = Vec<u8>;
type Signature = AnySignature;
type Extra = DefaultExtra<DefaultConfig>;
type UnEx = UncheckedExtrinsic<Address, Call, Signature, Extra>;


fn to_bytes(hex_str: &str) -> Vec<u8> {
    let hex_str = hex_str.strip_prefix("0x").expect("0x should prefix hex encoded bytes");
    hex::decode(hex_str).expect("valid bytes from hex")
}

fn main(){
        let mut ext="0x280403000b0385e91f7f01";
        let input = &mut &*to_bytes(ext);
        let uncheck_extrinsic = UnEx::decode(input);
        println!("block extrinsics = {:?}", uncheck_extrinsic);  // Got  `Not enough data to decode vector"` error
}
```

output 

`block extrinsics = Err(Error { cause: None, desc: "Not enough data to decode vector" })`

I want a detailed polkadot's extrinsics decoding method or code.
What am I doing wrong?

**Comment by dvdplm** [comment]
> `let mut ext="0x280403000b0385e91f7f01";`

This doesn't look like it is the full extrinsic payload, it's way too short. Can you look into obtaining a better test vector perhaps?

**Comment by jsdw** [comment]
As @dvdplm, the error basically means that the thing you're trying to decode to is expecting more bytes than you are providing.

Decoding extrinsics yourself is a tricky affair, which is why libraries like `subxt` attempt to do some of it for you.

Unfortunately there isn't a wealth of documentation on the exact extrinsic format and how to go about decoding it. I can point you at this example where I *encode* a transaction (may be a little out of date but should be about right): https://github.com/paritytech/polkadot-interaction-examples-rs/blob/main/src/bin/05_transfer_balance.rs

It's not quite as simple as simply knowing the correct SCALE type to decode as (you'll see a "special" version + "is there a signature" byte near the front).

Could you share with us what you're trying to achieve, and that'll help determine whether `subxt` is a good fit for you (or indeed could do with a new feature or two)?

**Comment by paperfrog1228** [comment]
@jsdw 
I'm trying to decode and encode extrinsics. First of all, I'm trying decoding first.
Your opinion received through Discord yesterday was very helpful.

But other people recommend subxt a lot.
There is also a reason that subxt would be better if both decoding and encoding functions were needed.

The above example follows the issue below.
https://github.com/paritytech/subxt/issues/125

Is it right to decode in desub and encode in subxt?

**Comment by jsdw** [comment]
Both libraries really have a slightly "higher" purpose which just happens to involve decoding and encoding things.

Subxt can be used to generate an interface at compile time to a node. Using this interface we can make transactions, subscribe to events, and obtain storage data (each of which involves some degree of encoding and decoding).

Desub is more focused on being able to dynamically decode storage (inc events) and transactions as part of substrate-archive, which reads this data into an SQL database. It's a bit more specific.

So the real question I think is, _why_ are you trying to decode and encode extrinsics? If you'd like to be able to communicate and monitor the state of a substrate based node that you're building for instance, then having a play with `subxt` (and not worrying too much about the specifics of the decoding and encoding) is probably your best starting point. If you are just playing around with encoding and decoding to learn what's going on, my example linked above might be a good place to start (alas it is not well documented otherwise right now, but people are working on it). If you'd like to write something which can target multiple substrate nodes at once, the compile-time API substrate generates may not be ideal, and having more of a play with `desub-current` might be fruitful (though note that it was not built to encode transactions, only decode them).
