### ISSUE TITLE
wss support for subxt metadata

### ISSUE THREAD

**Issue by gilescope** [paritytech/subxt#512]
It would be nice if we could supply a websocket address rather than a url as it's easy to get the ws address of parachain nodes using polkadot-js. (we can just select any parachain and then switch to custom to see what ws address we're looking at)

```
subxt metadata --url wss://kusama.public.curie.radiumblock.co/ws
```

Figuring out what the equivalent http url is seem more hit and miss... it would be great if subxt metadata worked wtih ws/wss as well as http. (This is assuming that we can get the metadata from a websocket - I think we can?)

**Comment by niklasad1** [comment]
Sounds like a good idea to me.

[subxt cli](https://github.com/paritytech/subxt/blob/master/cli/Cargo.toml#L23) is using `ureq` probably because it's more light weight than `jsonrpsee`

@ascjones can probably explain why :)

**Comment by gilescope** [comment]
subwasm can do either which is nice, but subwasm only saves json down at the moment, not the bin format. (That bin format doesn't half look like strings when you look at it. - I bet it would compress down again to something a lot smaller)

**Comment by ascjones** [comment]
> [subxt cli](https://github.com/paritytech/subxt/blob/master/cli/Cargo.toml#L23) is using `ureq` probably because it's more light weight than `jsonrpsee`

Exactly it's just a bit smaller if all you want to install is the `subxt-cli`, and originally the code was copied across from the standalone https://github.com/ascjones/subsee/ project.

But as you say it would be nice to use the `ws` address, so I wouldn't have a problem with using `jsonrpsee` instead since it is obviously already a workspace dependency.
