### ISSUE TITLE
access raw metadata

### ISSUE THREAD

**Issue by gilescope** [paritytech/subxt#523]
Would be nice to be able to get the raw bytes and cache them for later. Also if the unprocessed bytes were made available then that could be used by other tools that might want to process the metadata other ways. Flexibility.

**Comment by jsdw** [comment]
You can use `client.rpc().metadata()` (guessing; I'd have to check the precise call) to get the SCALE encoded bytes, if that achieves what you want?

We could also store the raw bytes ourselves after making that call in the client, but it would mean more memory usage to do so, so I'm not entirely sure it's worth while.

We could also put the metadata bytes into the generated code (but I'd want to hide that behind a derive argument because it would bloat the code/executable size).

What would you use the cached metadata bytes for once you had them? Currently, you couldn't pass them back to subxt (we could expose the functionality to do that too, but it would have to come with a big "if the node has changed since this metadata was downloaded, we won't be able to properly validate that we can make calls etc any more, so use at your own risk" sort of thing).

**Comment by lexnv** [comment]
At the moment, we are storing the metadata as `RuntimeMetadataV14` internally.
Would access to the internal `RuntimeMetadataV14` suffice?

We could go one step further and transform the `RuntimeMetadataV14` back to bytes:

```rust
            let v14: RuntimeMetadataV14 = client.rpc().metadata();
            let prefixed = RuntimeMetadataPrefixed::from(v14);
            let blob = prefixed.encode();
```


The `client.rpc().metadata()` would translate/interpret the raw bytes:
```rust
    pub async fn metadata(&self) -> Result<Metadata, BasicError> {
        let bytes: Bytes = ...
            
        let meta: RuntimeMetadataPrefixed = Decode::decode(&mut &bytes[..])?;
        let metadata: Metadata = meta.try_into()?;
        Ok(metadata)
    }
```
If further flexibility is desirable, we could extend the RPC methods to expose a `metadata_raw()` method for just fetching the bytes.

**Comment by jsdw** [comment]
The latest release exposes a `subxt_metadata::Metadata` thing, which can be converted into V14 or V15 (unstable) `frame-metadata` and scale encoded or whatever. We won't necessarily always be able to convert `Metadata` into every prior version of `frame-metadata` (depends on the extent of the changes) but I think that's the best Subxt will offer here. Otherwise you'll have to use the RPCs (or generated Runtime APi interface soon) to ask for whatever meatdata bytes you want :)
