### ISSUE TITLE
Return fee details for an Extrinsic

### ISSUE THREAD

**Issue by daniel-savu** [paritytech/subxt#527]
Is there a way to check the exact `final_fee` that the signer of an extrinsic was charged? The best I could think of was approximating using weights. Thank you!

**Comment by jsdw** [comment]
I'm not sure off the top of my head! Having a bit of a look around, I'm not sure it's obvious from the events that come back for a transaction exactly which fees were paid. There is more detail on which fees are paid here: https://wiki.polkadot.network/docs/learn-transaction-fees

It may be that the most robust way to know exactly what you paid for a transaction is to check your balance before and after submitting it (of course ignoring any non-fee amounts you may be transferring).

Perhaps it's worth asking a question at https://substrate.stackexchange.com; if you find a specific set of steps to take, we can help you run through those steps using subxt.

**Comment by jsdw** [comment]
Just FYI, I dug into this myself and answered your stackexchange post (https://substrate.stackexchange.com/a/4224/474). I hope that helps!

Now that I understand it better, and assuming that all turns out to be reliable (so far it seems that way), I'll consider adding a feature to subxt to return the `partial_fee` for some extrinsic. (you'll probably always have to manually add on any tip paid, since the tip paying stuff can vary by chain and subxt doesn't have a reliable way to get at it.

**Comment by savudani8** [comment]
Thank you very much for your answer! We'll have a think about whether it's worth calculating this fee ourselves since the ` transactionPayment::TransactionFeePaid` event seems to be coming soon.

**Comment by jsdw** [comment]
Just to add, I think that the goal here should be to add something like:

```rust
pub fn partial_fee_estimate(&self) -> u64
```

to `SubmittableExtrinsic`. This will use `payment_queryInfo` to return the _estimated_ partialFee.

Later, we could also add:

 ```rust
pub fn partial_fee(&self) -> u64
```

to `TxEvents`. This could look for the `TransactionFeePaid` event (when it exists) and use that.

We could assume that fees are calculated as they are on polkadot and use the ExtrinsicSuccess event etc (see above stackexchange link) but it's probably wrong to bake in that assumption.
