### ISSUE TITLE
subxt metadata doesn't work with polkadot master (rev commit 4aea24)

### ISSUE THREAD

**Issue by niklasad1** [paritytech/subxt#531]
```
error: Failed to decode metadata: Could not decode `RuntimeMetadataPrefixed.1`:
           Could not decode `RuntimeMetadata`, variant doesn't exist
  --> utils/staking-miner/src/main.rs:51:1
   |
51 | / #[subxt::subxt(
52 | |     runtime_metadata_path = "polkadot.scale",
53 | |     derive_for_all_types = "Clone, PartialEq",
54 | |     derive_for_type(type = "sp_core::crypto::AccountId32", derive = "Eq, Ord, PartialOrd"),
55 | |     derive_for_type(type = "sp_arithmetic::per_things::PerU16", derive = "Copy, Default")
56 | | )]
   | |__^
   |
   = note: this error originates in the attribute macro `subxt::subxt` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by lexnv** [comment]
### Repro case
- Start polkadot from `6ed790ba2` - `polkadot --dev --tmp`
- Fetch metadata to subxt artifacts - cargo run --release -p subxt-cli -- metadata > artifacts/polkadot_metadata.scale`
- Run an example `cargo run --example rpc_call`

Metadata seemed to suffer some major changes increasing from `323K` to `1.5M`.

**Comment by lexnv** [comment]
The issue seems to be with the `runtime_metadata_path = "polkadot.scale"`.

Most probably your `polkadot.scale` is not generated properly. It needs to be in a binary format.

This is the same mistake I made above. The CLI seems to produce by default the JSON format for the metadata.

Note the `--format bytes` 😄 

```
cargo run --release -p subxt-cli -- metadata --format bytes > polkadot.scale
```

Could you double-check if your metadata is in plain json text?

Thanks

**Comment by jsdw** [comment]
I do think that the cli tool should default to producing bytes, since that's what the library expects.

**Comment by lexnv** [comment]
Have updated #533 to reflect the `bytes` default.
