### ISSUE TITLE
QUESTION: why `subxt` is not versioned the same way Substrate is?

### ISSUE THREAD

**Issue by armyhaylenko** [paritytech/subxt#580]
Hey peeps, I was trying to integrate `subxt` within a substrate client, which is rigidly versioned, according to Substrate releases (`polkadot-v0.9.x`). Weird errors were happening & I quickly realized that the versions of `sp_core` and other libs didn't match, and in the `Cargo.toml` of the `subxt` crate, the `sp_core` dependency is specified like [this](https://github.com/paritytech/subxt/blob/6d7a6c9388f28ae0c49dfb994633ea5147a3791d/subxt/Cargo.toml#L38).
Question: Is this the intended maintenance tactic? Or do you plan to do releases together with Substrate eventually?

**Comment by ascjones** [comment]
In order to release `subxt` to crates.io, all dependencies need to also be on crates.io, so they will only ever be the latest released version. Substrate/polkadot releases are currently only on github and will be for the foreseeable future. 

The workaround would be to create your own branch/fork of subxt which changes those dependencies to point at the relevant branch on github.

Another question is why you are intending to use `subxt` from within the substrate client itself? What do you mean exactly?

**Comment by jsdw** [comment]
Substrate doesn't really have a good story for releases at the moment, which can be quite annoying for `subxt`. In order for `subxt` to rely on substrate primitive crates, we need to publish them to crates.io, which does not happen by default.

What this means practically is that we manually publish substrate primitive crates like `sp-core`, and if we spot some breakage (ie subxt stops working with the latest polkadot release) we have to manually push to release/publish a new version of the primitive crate that's had a breaking change (and all of it s dependencies). 

To try and spot such breakages, we do run nightly tests against Substrate binaries; if they fail, an issue pops up here for us to investigate. (That said, these nightly tests have stopped working due to those nightly releases not updating in the past; it's hard to check for that, so we also rely on bug reports from users in the event that those nightlies aren't updated as they should be).

Polkadot on the other hand has a better release story that's becoming more consistent with an aim of a release every ~3 weeks, but our test suite is currently geared towards the more generic substrate client (mainly because changes appear there more quickly normally, and not every 3 weeks).

I do think that we should get better at testing subxt against latest polkadot releases, but on the whole the nightly substrate check should cater for this. Also, subxt intends to be more generic than just Polkadot, and so aligning releases with Polkadot doesn't necessarily make sense.

(Sorry @ascjones; I saw your reply pop up just now but I'll post this anyway!)

**Comment by armyhaylenko** [comment]
@ascjones 
> Another question is why you are intending to use `subxt` from within the substrate client itself? What do you mean exactly?
I'm running some offchain logic within the substrate node and communicating with the on-chain component using the runtime API. `subxt` has great macros & metadata fetch, which would help to create signed/unsigned/parametrized stuff muuuch easier than creating an `UncheckedExtrinsic`, throwing it onto the tx queue and so on. I wanted to try it out but sadly it's not versioned correctly. Maybe eventually I'll create a fork to use it, but it's just a bit sad that it's not maintained the same way Substrate is.

@jsdw 
> Also, subxt intends to be more generic than just Polkadot, and so aligning releases with Polkadot doesn't necessarily make sense.
Yep, I can see that.

Thanks for the answers guys. Since there is no timeline on when Substrate releases (or Polkadot releases - is `polkadot-v0.9.22` of the Substrate repo a Polkadot or Substrate release :)? ) are available on `crates.io`, maybe you need some help on creating the same release flow for subxt to use in production or semi-production projects rn?

**Comment by jsdw** [comment]
> I wanted to try it out but sadly it's not versioned the same way Substrate is. Maybe eventually I'll create a fork to use it, thanks for the idea.

If you need to be using the same crates as substrate is using at any point in time in subxt, I'd agree that forking is probably the way to go; we can't point to crates used in Substrate in subxt (and need to periodically release them to crates.io to be able to release subxt at all), but you certainly could in such a fork (I wonder whether using the `[patch]` stuff to replace said substrate crates in your fork would make it quite easy to keep uptodate).

> is polkadot-v0.9.22 of the Substrate repo a Polkadot or Substrate release :)?

It's just a tag pointing at the precise substrate commit used in the Polkadot release. The individual crates in substrate are never themselves released or published though.  

> maybe you need some help on creating the same release flow for subxt to use in production or semi-production projects rn?

What did you have in mind?

**Comment by armyhaylenko** [comment]
> What did you have in mind?

I have guys who would be happy to create local GitHub tags for `subxt` according to Substrate's `polkadot-vX.x.x` releases & be the co-maintainers of the repo.
Although it may not meet the `crates.io` release criteria you mentioned, it can help for projects that pair `subxt` with the Substrate client (like the one I'm working on).

**Comment by jsdw** [comment]
I don't quite understand; what would be the benefit of adding such tags? I wonder whether you could elaborate on what exactly you are proposing being done, perhaps with some example?

**Comment by armyhaylenko** [comment]
Say we have an enterprise blockchain, which has part of its logic on-chain and the other part off-chain, all within one node. So, `subxt` allows for easy runtime API creation, as well as for runtime upgrade subscriptions, while other means of creating such on-chain & off-chain communication is the custom runtime API (which allows us to do only unsigned transactions), direct tx queue submission (signed & unsigned txs) or using the `submitExtrinsicAndWatch` API (like polkadot.js).

Out of those three, `subxt` looks the most appealing - hence my desire to use it in a substrate node. But I can't do it cause I can't match Substrate versions (polkadot tags vs `subxt` releases). Hope this makes the issue clear :)

**Comment by jsdw** [comment]
I guess what you actually want is to have a version of subxt that uses the same versions of `sp_core` etc that are used in whatever version of substrate you're currently using (eg the polkadot-tagged ones if you track polkadot releases)?

Since those substrate crates aren't published, and so subxt cannot depend on them on `master`, I suspect that the easiest approach to do this would be to maintain a fork of `subxt` yourself and patch the substrate_dependencies to point to whichever version of substrate you're working off (possibly pointing to a locally checked out repo; whatever works for your setup). You may find breaking changes in some of the substrate crates that subxt depends on that require the odd change to subxt (or just break examples or tests or something) though, which would then need fixing up.

**Comment by armyhaylenko** [comment]
Alright :) Thanks for the extended explanations! It really helped 🤝
