### ISSUE TITLE
Support &'static str for runtime_metadata_path in the macro

### ISSUE THREAD

**Issue by kayabaNerve** [paritytech/subxt#602]
```rs
const METADATA: &str = concat!(env!("OUT_DIR"), "substrate.scale");
#[subxt::subxt(runtime_metadata_path = METADATA)]
```

```rs
#[subxt::subxt(runtime_metadata_path = concat!(env!("OUT_DIR"), "substrate.scale"))]
```

Both of these error with "expected literal", removing the ability to successfully use the out directory for metadata. It would be appreciated if one of the above patterns was possible.

**Comment by jsdw** [comment]
I agree; it'd be good to resolve this if possible!

I have a vague feeling though that I looked into it a while ago and it's not possible due to a a macro limitation: the subxt proc macro needs a resolved string to use to find the metadata, so if it's given eg `concat!(env!("OUT_DIR"), "substrate.scale")` (because rust doesn't evaluate the tokens before passing them in) it doesn't know what to do with it and has no way to evaluate it down to a string).

That all said, I ran into this issue too and my workaround was to write a `build.rs` file which spits out a rust file containing the macro like this:

https://github.com/paritytech/subxt/blob/6a2aabc2a698426711dc8566e0d20f507c43f1f7/testing/test-runtime/build.rs#L91

and then you can invlude that file somewhere to be used like so:

https://github.com/paritytech/subxt/blob/6a2aabc2a698426711dc8566e0d20f507c43f1f7/testing/test-runtime/src/lib.rs#L10

**Comment by kayabaNerve** [comment]
Thanks for the workaround :+1:

**Comment by jsdw** [comment]
I'm going to close this, as afaik, it is unfortunately not possible! It would be great though, I agree!
