### ISSUE TITLE
subxt codegen to autofind port

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/subxt#665]
1. My network main WS IP:PORT is 127.0.0.1:9988 running locall.
2. In polkadot.js I can connect and send extrinsics
3. Can generate TS client via ` ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --package @mynode/types/interfaces --endpoint ws://127.0.0.1:9988 --output src/types/interfaces`
4. Run `subxt codegen --url http://127.0.0.1:9988` 
Expected: generates rs code
Actual:
```
Error: 
   0: error fetching metadata from the substrate node
   1: http://127.0.0.1:9988/: Network Error: Unexpected EOF
   2: Unexpected EOF
```

Notes:
I look at logs, see I do not specify RPC port. 
I find it and run `subxt codegen --url http://127.0.0.1:37589`
Success.

So not clear why other tools fund RPC port, but not subxt?

**Comment by niklasad1** [comment]
Hey,

I don't follow what the issue but based on your example it looks like you use `http://127.0.0.1:9988` to connect to the WS server it will not work because the `subxt cli` will choose a `WS` or `HTTP` client depending on the URL that you provide.

Did I get that right or did you mean something else?

**Comment by dzmitry-lahoda** [comment]
oh, you are rigth. I though it would upgrade http to ws.
