### ISSUE TITLE
Should you generate traits/structs/types instead of `mod`s?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/subxt#669]
like
```
MyChain::Api::RuntimeTypes
MyChain::Api::tx().sudo()
```

- as types are better composable
- can implement macro to implement custom traits for types taking some shapes
- similar to what substrate runtime is - one big singleton type.
- like could make use of generic associative types later
- better works with ast macro

```
// 			error[E0573]: expected type, found module `dali_runtime`
//   --> utils/xcmp/src/main.rs:63:16
//    |
// 63 |             let call =  concat_idents!($network, _runtime)::Call::decode(&mut &$encoded[..])
//    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a type
			let call =  $network_runtime::Call::decode(&mut &$encoded[..])
```
mods are not good, tried to escape all

**Comment by jsdw** [comment]
Subxt already does use traits and structs to represent all of the generated things. `mod`s are just used to help organise these generated types into something more manageable/discoverable (and to give us a location to spit out all of the generated types into).

If you can provide some example of what you have in mind, that'd help me understand where you're coming from a bit better, but otherwise I'll close this as I don't think there's anything reasonable that we can change here.

**Comment by jsdw** [comment]
Gunna close for now, but you're welcome to re-open if you'd like to dig further into this!
