### ISSUE TITLE
How do we check Subxt's compatibility with Polkadot versions?

### ISSUE THREAD

**Issue by joshuacheong** [paritytech/subxt#756]
I am asking this on behalf of some of the builders in the community. Will subxt get an update for the v0.9.36 (Polkadot equivalent) branch? On a broader level - How do we check Subxt's compatibility with Polkadot versions?

**Comment by jsdw** [comment]
Subxt doesn't currently need to "track" versions of Polkadot for the most part, since many parts of the API that can change (the available pallets, transactions, storage items and such) are handled via metadat codegen, and so as long as you keep the metadata that you're using to generate the Subxt interface up to date, things will hopefully continue to work.

The exception is if Substrate/Polkadot changes some of the types uses in the general RPC interface (such as the shape of errors or reponses from certain methods). It generally should aim to avoid this, but from time to time such breakagaes do happen, and in many cases we can spot and fix them via our nightly test run using latest Substrate.

That all said, things do slip through and in those cases, we will give priority to resolving any such issues that are reported here :)

I hope that answers your question!
