### ISSUE TITLE
Update sp-core

### ISSUE THREAD

**Issue by MrishoLukamba** [paritytech/subxt#806]
It causes so many errors when using the latest version of sp-core, I think subxt should use the latest version

**Comment by DaviRain-Su** [comment]
you can patch used substrate dep version.

**Comment by dzmitry-lahoda** [comment]
Imho subxt, because depends on substrate, should follow their releases. Like ORML/Cumulus/Polkadot do.

**Comment by jsdw** [comment]
I'll be doing a release today with this in.

Substrate crates currently release weekly (ie don't follow Polkadot releases), so following Polkadot releases would not resolve anything here (we only (optionally) depend on Substrate crates after all).

However, the release plan as I understand it will be to release Substrate crates each time Polkadot is updated (and from the same branch that Polkadot uses), so at that point I'd want Subxt to keep roughly in line with that so that the Substrate dependencies are up to date :)
