### ISSUE TITLE
Add `at_latest()` to use instead of `.at(None)` in various places.

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#899]
Currently we have APIs like:

```rust
let client = OnlineClient::<PolkadotConfig>::new();

// fetch latest block:
let block = client.blocks().at(None).await?;
// fetch latest events:
let events = client.events().at(None).await?;
// fetch latest storage entries:
let storage = client.storage().at(None).await?;
```

Fetching the latest block/event/storage seems like a common need, and moreso, we only need the `async/await` + `Result` for one of the paths (ie when `None` is provided). So how about we split into two code paths:

```rust
let client = OnlineClient::<PolkadotConfig>::new();

// fetch latest block:
let block = client.blocks().at_latest().await?;
// fetch block at `block_hash`:
let block = client.blocks().at(block_hash); // no more Option

// fetch latest events:
let events = client.events().at_latest().await?;
// fetch events at `block_hash`:
let events = client.events().at(block_hash); // no more Option

// fetch latest storage entries:
let storage = client.storage().at_latest().await?;
// fetch storage at block hash:
let storage = client.storage().at(block_hash); // no more Option
```

That way, the interface is a bit clearer, and we avoid unnecessary result unwrapping etc where it's not needed (ie somebody could get a block hash via `client.blocks().at_latest().await?.hash()` and then pass that to subsequent calls and avoid the awaiting/unwrapping.

**Comment by tadeohepperle** [comment]
@jsdw I created a PR for this here: https://github.com/paritytech/subxt/pull/900
Unfortunately I think the alleviation of async + Result is only possible for the `storage_client.at(hash)` function, not for the other two, because they still make rpc requests in case the hash is already known. So for the `blocks_client` and the `events_client` I just created wrapper functions that make the API simpler.
